apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-election
  namespace: system
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create","delete","get","update"]
